"use client";
import { useEffect, useState } from "react";
import { PublicQuoteDecision } from "@/components/public-quote-decision";
import { rpc,camelize } from "@/lib/api-client";
import type { Quote } from "@/lib/types";

const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v/100);
type PublicQuote = Quote & {respondedAt?:string|null};
export default function PublicQuotePage(){
 const [quote,setQuote]=useState<PublicQuote|null>(null),[token,setToken]=useState(""),[error,setError]=useState("");
 useEffect(()=>{let active=true;const value=new URLSearchParams(window.location.search).get("token")||"";
 async function load(){try{if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value))throw new Error("Link de orçamento inválido.");
 const result=camelize(await rpc("ms_public_quote",{p_token:value},false)) as PublicQuote|null;
 if(!result)throw new Error("Orçamento não encontrado. Solicite um novo link à MS AUTO DETAILS.");
 if(active){setQuote(result);setToken(value);}}catch(e){if(active)setError(e instanceof Error?e.message:"Não foi possível carregar o orçamento.");}}
 void load();return()=>{active=false;};},[]);
 if(!quote)return <main className="grid min-h-screen place-items-center bg-neutral-950 p-5"><section className="max-w-lg rounded-2xl bg-white p-7"><h1 className="mb-3 text-xl font-black text-red-700">MS AUTO DETAILS</h1><p role={error?"alert":"status"}>{error||"Carregando orçamento…"}</p></section></main>;
 const calc=quote.calculation;return <main className="min-h-screen bg-neutral-950 px-4 py-8 text-neutral-900"><article className="mx-auto max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="border-b-4 border-red-700 bg-black p-6 text-white"><div className="flex items-center gap-3"><span className="text-4xl font-black italic text-red-600">MS</span><div><h1 className="text-xl font-black italic">AUTO DETAILS</h1><p className="text-sm text-neutral-300">Orçamento #{quote.id}</p></div></div></header><div className="space-y-6 p-6"><section><p className="text-sm text-neutral-500">Preparado para</p><h2 className="text-2xl font-bold">{quote.client}</h2><p className="mt-1 text-sm text-neutral-500">Emitido em {String(quote.date).slice(0,10).split("-").reverse().join("/")}{quote.validUntil?` · válido até ${String(quote.validUntil).slice(0,10).split("-").reverse().join("/")}`:""}</p></section><section className="space-y-3"><h3 className="font-bold">Serviços</h3>{calc?.items?.length?<div className="divide-y rounded-2xl border">{calc.items.map((item,index)=><div key={index} className="flex justify-between gap-4 p-4"><div><p className="font-medium">{item.description}</p><p className="text-sm text-neutral-500">{item.quantity} × {money(item.unitPriceCents)}</p></div><strong>{money(item.quantity*item.unitPriceCents)}</strong></div>)}</div>:<div className="flex justify-between rounded-2xl border p-4"><span>{quote.service}</span><strong>{money(quote.amountCents)}</strong></div>}{calc?.travelCents?<div className="flex justify-between px-1 text-sm"><span>Deslocamento</span><span>{money(calc.travelCents)}</span></div>:null}{calc?.extraCents?<div className="flex justify-between px-1 text-sm"><span>Outros adicionais</span><span>{money(calc.extraCents)}</span></div>:null}{calc?.discountCents?<div className="flex justify-between px-1 text-sm text-emerald-700"><span>Desconto</span><span>− {money(calc.discountCents)}</span></div>:null}<div className="flex justify-between border-t-2 border-black pt-4 text-xl font-black"><span>Total à vista</span><span>{money(quote.amountCents)}</span></div></section><PublicQuoteDecision token={token} status={quote.status} respondedAt={quote.respondedAt}/><p className="text-center text-xs leading-5 text-neutral-500">Página exclusiva deste orçamento. Nenhum dado da gestão da MS AUTO DETAILS é exibido.</p></div></article></main>}
