"use client";
import { useEffect,useState } from "react";
import { NativeSelectOption } from "@/components/ui/native-select";
import { parseMoneyInput } from "@/lib/quote-calculator";
import { parseQuantity,type Product } from "@/lib/operations";
import { ActionForm,Field,FormDialog,MethodField,SelectField,errorText,money,opsGet,opsMutate,quantityLabel,today,useOperations } from "@/components/operations-shared";

function ProductForm({product,onSaved}:{product?:Product;onSaved:()=>Promise<void>}) {
  const[name,setName]=useState(product?.name??""),[unit,setUnit]=useState(product?.unit??"ml"),[minimum,setMinimum]=useState(product?String(product.minimumMilli/1000):"");
  return <ActionForm label="Salvar produto" onSubmit={async()=>{await opsMutate({action:"product",id:product?.id,data:{name,unit,minimumMilli:parseQuantity(minimum)}});await onSaved();}}><Field label="Nome do produto" required maxLength={200} value={name} onChange={(e)=>setName(e.target.value)}/><SelectField label="Unidade de controle" disabled={Boolean(product)} value={unit} onChange={(e)=>setUnit(e.target.value as Product["unit"])}><NativeSelectOption value="ml">Mililitros (ml)</NativeSelectOption><NativeSelectOption value="g">Gramas (g)</NativeSelectOption><NativeSelectOption value="un">Unidades (un)</NativeSelectOption></SelectField><Field label={`Avisar reposição ao atingir (${unit})`} required inputMode="decimal" value={minimum} onChange={(e)=>setMinimum(e.target.value)} placeholder="Ex.: 500"/><p className="text-sm leading-6 text-neutral-500">1 litro = 1.000 ml. 1 kg = 1.000 g. Não converta gramas em ml. O aviso aparece quando o estoque chega ao mínimo ou fica abaixo dele.</p></ActionForm>;
}
export function StockForm({product,onSaved}:{product:Product;onSaved:()=>Promise<void>}) {
  const{data}=useOperations(),[key]=useState(()=>crypto.randomUUID()),[mode,setMode]=useState("purchase"),[qty,setQty]=useState(""),[cost,setCost]=useState(""),[expenseId,setExpenseId]=useState(""),[date,setDate]=useState(today),[method,setMethod]=useState("pix");
  return <ActionForm label="Confirmar entrada" onSubmit={async()=>{await opsMutate({action:"stock",data:{operationId:key,productId:product.id,quantityMilli:parseQuantity(qty),costCents:parseMoneyInput(cost),mode,expenseId:expenseId?Number(expenseId):undefined,date,method}});await onSaved();}}>
    <SelectField label="Como registrar esta entrada?" value={mode} onChange={(e)=>{setMode(e.target.value);setExpenseId("");setCost("");}}><NativeSelectOption value="purchase">Compra nova — lançar em Despesas</NativeSelectOption><NativeSelectOption value="existing">Compra já lançada — vincular despesa</NativeSelectOption><NativeSelectOption value="opening">Estoque inicial — não lançar despesa</NativeSelectOption></SelectField>
    {mode==="existing"&&<SelectField label="Despesa da compra (um produto por lançamento)" required value={expenseId} onChange={(e)=>{setExpenseId(e.target.value);const expense=data.expenses.find((r)=>r.id===Number(e.target.value));setCost(expense?(expense.amountCents/100).toFixed(2):"");}}><NativeSelectOption value="">Selecione a despesa</NativeSelectOption>{data.expenses.map((r)=><NativeSelectOption key={r.id} value={r.id}>#{r.id} · {r.description} · {money(r.amountCents)}</NativeSelectOption>)}</SelectField>}
    <Field label={`Quantidade adicionada (${product.unit})`} required inputMode="decimal" value={qty} onChange={(e)=>setQty(e.target.value)} placeholder={product.unit==="ml"?"Ex.: 5000 para 5 litros":"Quantidade"}/><Field label={mode==="opening"?"Valor estimado deste estoque (R$)":"Valor total da compra (R$)"} required readOnly={mode==="existing"} inputMode="decimal" value={cost} onChange={(e)=>setCost(e.target.value)}/><Field label="Data" type="date" required value={date} onChange={(e)=>setDate(e.target.value)}/>{mode==="purchase"&&<MethodField value={method} onChange={setMethod}/>}
    <p className="rounded-xl bg-red-50 p-3 text-sm leading-6 text-neutral-700">{mode==="purchase"?"Esta compra gera uma única despesa. Não lance a mesma compra manualmente em Despesas." : mode==="existing"?"A despesa escolhida não será lançada novamente. Ela não pode já estar vinculada a outro produto ou custo." : "Use para produtos que você já possui. Este valor serve apenas para calcular o custo do consumo; não altera seu saldo financeiro."}</p>
  </ActionForm>;
}
function StockHistory({product}:{product:Product}) {
  const[rows,setRows]=useState<{id:string;date:string;mode:string;quantityMilli:number;costCents:number;expenseId:number|null}[]|null>(null),[error,setError]=useState("");
  useEffect(()=>{let active=true;opsGet<NonNullable<typeof rows>>(`action=stock_history&id=${product.id}`).then((r)=>{if(active)setRows(r);}).catch((e)=>{if(active)setError(errorText(e));});return()=>{active=false;};},[product.id]);
  return error?<p role="alert">{error}</p>:rows===null?<p>Carregando...</p>:<ul className="space-y-2">{rows.length===0?<li>Nenhuma entrada registrada.</li>:rows.map((r)=><li key={r.id} className="rounded-xl border p-3"><p>{r.date.split("-").reverse().join("/")} · +{quantityLabel(r.quantityMilli)} {product.unit}</p><p className="text-sm text-neutral-500">{money(r.costCents)} · {r.mode==="opening"?"Saldo inicial sem despesa":`Despesa #${r.expenseId}`}</p></li>)}</ul>;
}
export function ProductsView() {
  const{products,onChanged}=useOperations();const low=products.filter((p)=>p.stockMilli<=p.minimumMilli);
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Produtos e estoque</h1><p className="mt-1 text-sm text-neutral-500">Compras entram no caixa uma vez. Consumo entra apenas no custo do serviço.</p></div><FormDialog label="Novo produto" title="Cadastrar produto" description="Depois do cadastro, registre a entrada do estoque.">{(close)=><ProductForm onSaved={async()=>{await onChanged();close();}}/>}</FormDialog></div>
    {low.length>0&&<div role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><p className="font-semibold">Precisa repor: {low.length} produto(s)</p><p className="mt-1 text-sm">{low.map((p)=>p.name).join(" · ")}</p></div>}
    {products.length===0&&<p className="rounded-xl border border-dashed p-8 text-center text-neutral-500">Cadastre seus produtos, quantidades e custos para começar.</p>}
    <div className="grid gap-3 md:grid-cols-2">{products.map((product)=><article key={product.id} className="space-y-4 rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{product.name}</h2>{product.stockMilli<=product.minimumMilli&&<span className="rounded-full bg-amber-50 px-3 py-1 text-sm font-medium text-amber-800">Repor estoque</span>}</div><div><p className="text-2xl font-bold">{quantityLabel(product.stockMilli)} <span className="text-sm font-normal">{product.unit}</span></p><p className="mt-1 text-sm text-neutral-500">Mínimo: {quantityLabel(product.minimumMilli)} {product.unit} · Valor em estoque: {money(product.stockValueCents)}</p></div><div className="flex flex-wrap gap-2"><FormDialog label="Entrada / compra" title={`Entrada: ${product.name}`} description="Informe a quantidade e escolha se a compra já foi lançada.">{(close)=><StockForm product={product} onSaved={async()=>{await onChanged();close();}}/>}</FormDialog><FormDialog label="Editar" title="Editar produto" description="A unidade não muda para preservar os consumos anteriores.">{(close)=><ProductForm product={product} onSaved={async()=>{await onChanged();close();}}/>}</FormDialog><FormDialog label="Entradas" title={`Entradas: ${product.name}`} description="As últimas 100 entradas do produto.">{()=> <StockHistory product={product}/>}</FormDialog></div></article>)}</div>
  </div>;
}
