"use client";
import { useEffect,useState } from "react";
import type { ProfitRow } from "@/lib/operations";
import { Field,errorText,money,opsGet,today,useOperations } from "@/components/operations-shared";

export function ProfitsView() {
  const{data}=useOperations(),[month,setMonth]=useState(today().slice(0,7)),[rows,setRows]=useState<ProfitRow[]|null>(null),[error,setError]=useState("");
  useEffect(()=>{let active=true;opsGet<ProfitRow[]>(`action=profits&month=${month}`).then((r)=>{if(active){setRows(r);setError("");}}).catch((e)=>{if(active)setError(errorText(e));});return()=>{active=false;};},[month,data]);
  const complete=(rows??[]).filter((r)=>r.status==="concluido"),margin=complete.reduce((total,r)=>total+r.amountCents-r.productCostCents-r.otherCostCents,0);
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Lucro por serviço</h1><p className="mt-1 text-sm text-neutral-500">Custos registrados por atendimento, separados do saldo financeiro.</p></div><Field label="Mês do serviço" type="month" required value={month} onChange={(e)=>{setRows(null);setMonth(e.target.value);}}/></div>
    <div className="rounded-xl bg-neutral-950 p-5 text-white"><p className="text-sm text-neutral-300">Resultado estimado dos serviços concluídos</p><p className="mt-2 text-3xl font-bold">{rows?money(margin):"—"}</p><p className="mt-2 text-sm text-neutral-300">Valor cobrado − produtos consumidos − outros custos vinculados. Não representa dinheiro já recebido e não inclui custos que você ainda não registrou.</p></div>
    {error?<p role="alert" className="text-red-700">{error}</p>:rows===null?<p>Carregando resultados...</p>:rows.length===0?<p>Nenhum serviço neste mês.</p>:<div className="grid gap-3">{rows.map((r)=>{const cost=r.productCostCents+r.otherCostCents,result=(r.status==="cancelado"?0:r.amountCents)-cost;return <article key={r.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">#{r.id} · {r.client}</h2><span className="text-sm text-neutral-500">{r.date.split("-").reverse().join("/")} · {r.status}</span></div><p className="mt-1 text-sm text-neutral-600">{r.service}</p><dl className="mt-4 grid gap-3 sm:grid-cols-4"><div><dt className="text-sm text-neutral-500">Valor cobrado</dt><dd>{money(r.status==="cancelado"?0:r.amountCents)}</dd></div><div><dt className="text-sm text-neutral-500">Produtos</dt><dd>{money(r.productCostCents)}</dd></div><div><dt className="text-sm text-neutral-500">Outros custos</dt><dd>{money(r.otherCostCents)}</dd></div><div><dt className="text-sm text-neutral-500">{r.status==="agendado"?"Margem prevista":"Resultado estimado"}</dt><dd className={`font-bold ${result<0?"text-red-700":"text-emerald-700"}`}>{money(result)}</dd></div></dl>{cost===0&&<p className="mt-3 text-sm text-amber-800">Nenhum custo registrado. O resultado ainda pode estar superestimado.</p>}</article>;})}</div>}
    <p className="text-sm leading-6 text-neutral-500">Registre consumo e outros custos em Agenda → Ordem de serviço. A compra dos produtos já entrou em Despesas; o consumo não é descontado novamente do caixa.</p>
  </div>;
}
