"use client";
/* Private Blob URLs require a regular img element. */
/* eslint-disable @next/next/no-img-element */
import { useEffect,useId,useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelectOption } from "@/components/ui/native-select";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { parseMoneyInput } from "@/lib/quote-calculator";
import { concentrateMilli,parseQuantity,usageCost,type JobDetails,type WorkOrder } from "@/lib/operations";
import type { Appointment } from "@/lib/types";
import { ActionForm,ConfirmAction,Field,FormDialog,MethodField,SelectField,errorText,money,opsGet,opsMutate,quantityLabel,today,useOperations } from "@/components/operations-shared";
import { apiFetch } from "@/lib/api-client";

function PrivatePhoto({id,alt}:{id:string;alt:string}){const[src,setSrc]=useState("");useEffect(()=>{let active=true,url="";apiFetch(`/api/photos?id=${id}`).then(async r=>{if(!r.ok)throw new Error();url=URL.createObjectURL(await r.blob());if(active)setSrc(url);}).catch(()=>{});return()=>{active=false;if(url)URL.revokeObjectURL(url);};},[id]);return src?<img src={src} alt={alt} loading="lazy" className="aspect-square w-full rounded-lg object-cover"/>:<div className="grid aspect-square place-items-center rounded-lg bg-neutral-100 text-sm text-neutral-500">Carregando foto…</div>}

export function ConsumptionForm({appointmentId,onSaved}:{appointmentId:number;onSaved:()=>Promise<void>}) {
  const{products}=useOperations(),[key]=useState(()=>crypto.randomUUID()),[productId,setProductId]=useState(""),[amount,setAmount]=useState(""),[mode,setMode]=useState("direct"),[water,setWater]=useState(""),[date,setDate]=useState(today);
  const product=products.find((p)=>p.id===Number(productId));let used=0,cost:number|null=null,previewError="";
  try { if(product&&amount){if(mode==="diluted"&&!water.trim())throw new Error("Informe a diluição realmente utilizada.");const total=parseQuantity(amount);used=mode==="diluted"?concentrateMilli(total,Number(water)):total;cost=usageCost(product,used);} } catch(error){previewError=errorText(error);}
  return <ActionForm label="Registrar consumo e baixar estoque" onSubmit={async()=>{if(!product||!used||cost===null)throw new Error(previewError||"Escolha o produto e a quantidade utilizada.");await opsMutate({action:"consume",data:{operationId:key,productId:product.id,appointmentId,quantityMilli:used,date}});await onSaved();}}>
    <SelectField label="Produto utilizado" required value={productId} onChange={(e)=>{setProductId(e.target.value);setMode("direct");setAmount("");}}><NativeSelectOption value="">Selecione o produto</NativeSelectOption>{products.map((p)=><NativeSelectOption key={p.id} value={p.id}>{p.name} · {quantityLabel(p.stockMilli)} {p.unit}</NativeSelectOption>)}</SelectField>
    {product?.unit==="ml"&&<SelectField label="Como você mediu o consumo?" value={mode} onChange={(e)=>setMode(e.target.value)}><NativeSelectOption value="direct">Quantidade de produto puro/concentrado</NativeSelectOption><NativeSelectOption value="diluted">Quantidade de solução já diluída</NativeSelectOption></SelectField>}
    <Field label={`${mode==="diluted"?"Solução diluída utilizada":"Produto utilizado"} (${product?.unit??"unidade"})`} required inputMode="decimal" value={amount} onChange={(e)=>setAmount(e.target.value)}/>
    {mode==="diluted"&&<><Field label="Partes de água para 1 parte de produto" type="number" required min={0} max={1000} step={1} value={water} onChange={(e)=>setWater(e.target.value)}/><p className="text-sm text-neutral-500">Ex.: 1 de produto + 19 de água. Informe a proporção que você realmente usou, conforme o rótulo; a plataforma não recomenda diluições.</p></>}
    <Field label="Data do consumo" type="date" required value={date} onChange={(e)=>setDate(e.target.value)}/>
    {cost!==null&&<div className="rounded-xl bg-red-50 p-3 text-sm"><p>Baixa no estoque: <strong>{quantityLabel(used)} {product?.unit}</strong></p><p className="mt-1">Custo estimado no serviço: <strong>{money(cost)}</strong></p></div>}{previewError&&<p className="text-sm text-red-700">{previewError}</p>}
    <p className="text-sm leading-6 text-neutral-500">Usa o custo médio do estoque. Não cria despesa nem desconta o dinheiro novamente. O custo confirmado fica salvo neste serviço.</p>
  </ActionForm>;
}
function OtherCostForm({appointmentId,onSaved}:{appointmentId:number;onSaved:()=>Promise<void>}) {
  const{data}=useOperations(),[key]=useState(()=>crypto.randomUUID()),[mode,setMode]=useState("existing"),[expenseId,setExpenseId]=useState(""),[description,setDescription]=useState(""),[amount,setAmount]=useState(""),[date,setDate]=useState(today),[method,setMethod]=useState("pix");
  return <ActionForm label="Registrar custo do serviço" onSubmit={async()=>{await opsMutate({action:"job_cost",data:{operationId:key,appointmentId,mode,expenseId:expenseId?Number(expenseId):undefined,description,amountCents:parseMoneyInput(amount),date,method}});await onSaved();}}>
    <SelectField label="Esta despesa já foi lançada?" value={mode} onChange={(e)=>setMode(e.target.value)}><NativeSelectOption value="existing">Sim — vincular sem lançar novamente</NativeSelectOption><NativeSelectOption value="new">Não — criar despesa e vincular</NativeSelectOption></SelectField>
    {mode==="existing"&&<SelectField label="Despesa existente" required value={expenseId} onChange={(e)=>{setExpenseId(e.target.value);const r=data.expenses.find((v)=>v.id===Number(e.target.value));setDescription(r?.description??"");setAmount(r?(r.amountCents/100).toFixed(2):"");}}><NativeSelectOption value="">Selecione a despesa</NativeSelectOption>{data.expenses.map((e)=><NativeSelectOption key={e.id} value={e.id}>#{e.id} · {e.description} · {money(e.amountCents)}</NativeSelectOption>)}</SelectField>}
    <Field label="Descrição do custo" required maxLength={300} value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Ex.: ajudante ou combustível"/><Field label="Parte do valor atribuída a este serviço (R$)" required inputMode="decimal" value={amount} onChange={(e)=>setAmount(e.target.value)}/><Field label="Data da despesa" type="date" required value={date} onChange={(e)=>setDate(e.target.value)}/>{mode==="new"&&<MethodField value={method} onChange={setMethod}/>}
    <p className="text-sm text-neutral-500">Produtos são registrados em Consumo, não aqui. Uma despesa pode ser dividida entre serviços sem ultrapassar seu valor total. {mode==="new"?"Esta opção cria uma nova saída no caixa.":"Esta opção não cria uma nova saída no caixa."}</p>
  </ActionForm>;
}
export function WorkOrderForm({appointment,order,onSaved}:{appointment:Appointment;order:WorkOrder|null;onSaved:()=>Promise<void>}) {
  const{data}=useOperations(),prefix=useId(),[itemDescription,setItemDescription]=useState(order?.itemDescription??""),[conditionNotes,setConditionNotes]=useState(order?.conditionNotes??"");
  const[items,setItems]=useState(order?.checklist??(data.quotes.find((q)=>q.id===appointment.quoteId)?.calculation?.items.map((r)=>({label:r.description.slice(0,150),done:false}))??[{label:appointment.service.slice(0,150),done:false}])),[newItem,setNewItem]=useState("");
return <ActionForm label="Salvar ordem de serviço" onSubmit={async()=>{await opsMutate({action:"work_order",id:appointment.id,data:{itemDescription,conditionNotes,checklist:items}});await onSaved();}}><Field label="Veículo ou estofado atendido" maxLength={500} value={itemDescription} onChange={(e)=>setItemDescription(e.target.value)} placeholder="Ex.: modelo, placa, tecido, cor ou quantidade"/><div className="space-y-2"><Label htmlFor={`${prefix}-condition`}>Condição inicial e observações</Label><Textarea id={`${prefix}-condition`} maxLength={4000} value={conditionNotes} onChange={(e)=>setConditionNotes(e.target.value)} placeholder="Manchas, avarias e detalhes combinados com o cliente"/></div><div className="space-y-3"><h3 className="font-semibold">Checklist do trabalho</h3>{items.map((item,index)=><div key={index} className="flex items-center gap-3 rounded-lg border p-3"><Checkbox id={`${prefix}-${index}`} checked={item.done} onCheckedChange={(checked)=>setItems((all)=>all.map((row,i)=>i===index?{...row,done:checked===true}:row))}/><Label htmlFor={`${prefix}-${index}`} className="flex-1 break-words leading-6">{item.label}</Label><Button type="button" variant="ghost" size="sm" aria-label={`Remover ${item.label}`} onClick={()=>setItems((all)=>all.filter((_,i)=>i!==index))}>Remover</Button></div>)}<div className="flex gap-2"><Input aria-label="Novo item do checklist" value={newItem} maxLength={150} onChange={(e)=>setNewItem(e.target.value)} placeholder="Novo procedimento"/><Button type="button" variant="outline" disabled={!newItem.trim()||items.length>=50} onClick={()=>{setItems([...items,{label:newItem.trim(),done:false}]);setNewItem("");}}>Adicionar</Button></div></div></ActionForm>;
}
function Photos({appointmentId,photos,onSaved}:{appointmentId:number;photos:JobDetails["photos"];onSaved:()=>Promise<void>}) {
  const[file,setFile]=useState<File|null>(null),[stage,setStage]=useState("before"),[fileKey,setFileKey]=useState(0);
  return <div className="space-y-5"><ActionForm label="Salvar foto" onSubmit={async()=>{if(!file)throw new Error("Escolha uma foto.");if(file.size>5*1024*1024)throw new Error("Use uma foto de até 5 MB.");const form=new FormData();form.append("file",file);form.append("stage",stage);form.append("appointmentId",String(appointmentId));const response=await apiFetch("/api/photos",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||"Não foi possível salvar a foto.");setFile(null);setFileKey((v)=>v+1);await onSaved();}}><SelectField label="Momento da foto" value={stage} onChange={(e)=>setStage(e.target.value)}><NativeSelectOption value="before">Antes</NativeSelectOption><NativeSelectOption value="after">Depois</NativeSelectOption></SelectField><Field key={fileKey} label="Foto do serviço" type="file" accept="image/jpeg,image/png,image/webp" required onChange={(e)=>setFile(e.target.files?.[0]??null)}/><p className="text-sm text-neutral-500">JPG, PNG ou WebP, até 5 MB por foto e 12 fotos por serviço. As fotos ficam privadas na sua plataforma.</p></ActionForm><div className="grid grid-cols-2 gap-3">{photos.map((photo)=><figure key={photo.id} className="space-y-2 rounded-xl border p-2"><PrivatePhoto id={photo.id} alt={`${photo.stage==="before"?"Antes":"Depois"} do serviço #${appointmentId}`}/><figcaption className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>{photo.stage==="before"?"Antes":"Depois"}</span><ConfirmAction label="Remover foto" description="Esta foto será excluída definitivamente. Os outros dados do serviço não mudam." onConfirm={async()=>{const response=await apiFetch("/api/photos",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:photo.id})});if(!response.ok)throw new Error("Não foi possível remover a foto.");await onSaved();}}/></figcaption></figure>)}</div></div>;
}
function JobContent({appointment}:{appointment:Appointment}) {
  const{onChanged,clients}=useOperations(),[details,setDetails]=useState<JobDetails|null>(null),[error,setError]=useState(""),[version,setVersion]=useState(0),[notice,setNotice]=useState(""),[clientId,setClientId]=useState(String(appointment.clientId??""));
  useEffect(()=>{let active=true;opsGet<JobDetails>(`action=job&id=${appointment.id}`).then((r)=>{if(active)setDetails(r);}).catch((e)=>{if(active)setError(errorText(e));});return()=>{active=false;};},[appointment.id]);
  async function refresh(){setDetails(await opsGet<JobDetails>(`action=job&id=${appointment.id}`));await onChanged();setVersion((v)=>v+1);setNotice("Dados do serviço atualizados.");}
  if(error)return <p role="alert" className="text-red-700">{error}</p>;if(!details)return <p>Carregando ordem de serviço...</p>;
  const productCost=details.usage.filter((u)=>!u.reversed).reduce((sum,u)=>sum+u.costCents,0),otherCost=details.costs.reduce((sum,c)=>sum+c.amountCents,0),margin=(appointment.status==="cancelado"?0:appointment.amountCents)-productCost-otherCost;
  return <div className="space-y-5"><div className="rounded-xl bg-red-50 p-4 text-sm"><p className="font-semibold">{appointment.client} · {appointment.date.split("-").reverse().join("/")} às {appointment.time}</p><p className="mt-1">{appointment.service}</p><p className="mt-2">Produtos: {money(productCost)} · Outros custos: {money(otherCost)}</p><p className="mt-1 font-semibold">Resultado estimado: {money(margin)}</p><p className="mt-1 text-neutral-500">Considera apenas custos registrados. Não altera o saldo financeiro.</p></div>{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}
<Tabs defaultValue="order"><TabsList className="grid w-full grid-cols-3"><TabsTrigger value="order">Ordem</TabsTrigger><TabsTrigger value="costs">Custos</TabsTrigger><TabsTrigger value="photos">Fotos</TabsTrigger></TabsList><TabsContent value="order" className="space-y-5 pt-3"><WorkOrderForm appointment={appointment} order={details.workOrder} onSaved={refresh}/>{clients.length>0&&<ActionForm label="Vincular cliente" onSubmit={async()=>{await opsMutate({action:"assign_client",resource:"appointments",id:appointment.id,clientId:Number(clientId)});await refresh();}}><SelectField label="Cliente do cadastro" required value={clientId} onChange={(e)=>setClientId(e.target.value)}><NativeSelectOption value="">Selecione</NativeSelectOption>{clients.map((c)=><NativeSelectOption key={c.id} value={c.id}>{c.name} · {c.phone}</NativeSelectOption>)}</SelectField></ActionForm>}</TabsContent>
      <TabsContent value="costs" className="space-y-6 pt-3">{appointment.status!=="cancelado"&&<><section className="space-y-3"><h3 className="text-lg font-semibold">Consumo de produtos</h3><ConsumptionForm key={`usage-${version}`} appointmentId={appointment.id} onSaved={refresh}/></section><section className="space-y-3 border-t pt-5"><h3 className="text-lg font-semibold">Outros custos</h3><OtherCostForm key={`cost-${version}`} appointmentId={appointment.id} onSaved={refresh}/></section></>}
      <section className="space-y-3 border-t pt-5"><h3 className="font-semibold">Custos registrados</h3>{details.usage.length===0&&details.costs.length===0&&<p className="text-sm text-neutral-500">Nenhum custo registrado ainda.</p>}{details.usage.map((u)=><div key={u.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 text-sm"><div><p>{u.productName} · {quantityLabel(u.quantityMilli)} {u.unit}</p><p className={u.reversed?"text-neutral-400 line-through":"text-neutral-600"}>{money(u.costCents)}{u.reversed?" · Consumo estornado":""}</p></div>{!u.reversed&&<ConfirmAction label="Estornar consumo" description="Use apenas para corrigir um consumo lançado por engano. A quantidade e o custo voltarão ao estoque e sairão do custo deste serviço. O caixa não muda." onConfirm={async()=>{await opsMutate({action:"reverse_usage",id:u.id});await refresh();}}/>}</div>)}{details.costs.map((c)=><div key={c.id} className="rounded-xl border p-3 text-sm"><p>{c.description} · {money(c.amountCents)}</p><p className="mt-1 text-neutral-500">Despesa #{c.expenseId} vinculada, sem duplicação.</p></div>)}</section></TabsContent>
      <TabsContent value="photos" className="pt-3"><Photos appointmentId={appointment.id} photos={details.photos} onSaved={refresh}/></TabsContent>
    </Tabs></div>;
}
export function WorkOrderButton({appointment}:{appointment:Appointment}) {
  return <FormDialog label="Ordem de serviço" title={`Ordem de serviço #${appointment.id}`} description="Checklist, fotos, produtos utilizados e custos deste atendimento." wide>{()=> <JobContent appointment={appointment}/>}</FormDialog>;
}
